apiVersion: v1
data:
    password: ENC[AES256_GCM,data:fsYHp+XFwWYHhXGN,iv:ana0cYmEMPk6EMR8FgmmDVNiZ/ZDxgHLWE937OcHdIM=,tag:Ob2BeqTMGq8hk2Mp28Yelw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: redis-auth
    namespace: redis
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-03-19T15:21:26Z'
    mac: ENC[AES256_GCM,data:40rHifHDoUcJXyQWiEPlztTDDAO+yjrPNVK0Sp1cWN55QomTr8LhBRqt121CMjA3zhCb3EVc9nv0Us2FRHi6jQ2IsuZmlDBDEWcVB/1BpUHugBt08gD+gqoKJbuMJL68imsZqRDS2K0fcASQeEf6zBXpii2raaoCb+lasq2nqzU=,iv:+y3ac+Dt4XXIlVAwUMZF0P+2j5BBZU3eCheg15dNUnk=,tag:m1z/4tK8/e468X34ZQJzVA==,type:str]
    pgp:
    -   created_at: '2021-03-19T15:21:25Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/wwv0+7G4qSARAAgeS6COSlImTuoOJdKhrYgoar9slh4PLsijg//YhEBest
            5zwrJXPo3UV7eCSmf6Hzg3UPPrBC5Td6UZj9mFOJj9dNKJWHIni0rU7UvLaAN3+v
            A1yMMclAwVMEXe7asXqCcTVk9wZp/bgqRZ/msOBZXuWzwm35LJJ+lW5CqicPM015
            FN/GyYgLrNJhdZSSOHmDo4zt7gikAyNzFLBpcM6d903GjybcAS5d4LuqLKBANE9k
            cvortyX461k6l6HmPX3jcEaf+CVQlQWSiojHMNkyawsVJVNGTZkL9N4xiI6dW2dP
            1imYGXz5pUonXv7KefwTy6FtWXCgV9PSSbTeMA5apv7TgKEv1hRsf+OfXwUT6biZ
            9jhIPueJoLBXFQCmZ/lTX46dmBFPOBiWtbjbBOaGMzUQwJG1qJI9SZVYHK6Rn1DL
            abqeWdWAVsd/8zcciglLKUbze/m1yIrbRPtvrbNYA7rKs2dk8tk835zX8tpIBYmB
            8ajWUV8F+XM0C29o8zXiQRcv84V1lmrb+O0SBfe2K9+0vULDUbhzgBjb7vfXctnj
            oLwPe5IPBKrg+GcMV5tT3ARwnQEu9lpU6ua6ky651eO3iLapp5ATByg9XL3UvNoO
            4QGMdGiGs/RhzE6MiV9KgPvPhI4zRXDUUveuLYgOM7TLmzG4VbDDTiQZAsXVoW/S
            XgHR9UCjmQ9zijGPjzB7liq0Wv3gsHysIJUxxqQzCBMn3ksTsQRfsmrKzcohhm/G
            liFWuqilYbSPXIS9fjcHM0TsBjBsoRPHvIpuUwzAr1vKgx8+6Qt2RBl3n1XuUXw=
            =zt1+
            -----END PGP MESSAGE-----
        fp: 0F0D995FDDDB033F5122DF0D85EB712FD879B0A4
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1

